# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='risk_index',
            new_name='risk_assessment_score',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='risk_assessment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
