# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 19:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171110_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='selected_coins',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bitcoin', 'Bitcoin'), ('bitcoin_cash', 'Bitcoin Cash'), ('dash', 'Dash'), ('ethereum', 'Ethereum'), ('ethereum_classic', 'Ethereum Classic'), ('litecoin', 'Litecoin'), ('monero', 'Monero'), ('neo', 'NEO'), ('ripple', 'Ripple'), ('zcash', 'Zcash')], default=[], max_length=84),
            preserve_default=False,
        ),
    ]
