# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171005_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
    ]
