# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171017_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
