# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_balance',
            new_name='account_value',
        ),
    ]
