# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=30),
            preserve_default=False,
        ),
    ]
