# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 22:59
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171110_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='selected_coins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bitcoin', 'Bitcoin'), ('bitcoin_cash', 'Bitcoin Cash'), ('dash', 'Dash'), ('ethereum', 'Ethereum'), ('ethereum_classic', 'Ethereum Classic'), ('litecoin', 'Litecoin'), ('monero', 'Monero'), ('neo', 'NEO'), ('ripple', 'Ripple'), ('zcash', 'Zcash')], max_length=84, null=True),
        ),
    ]
