# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='stripe_charge_id',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
