# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_account_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='exchange',
            field=models.CharField(choices=[('GDAX', 'GDAX')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
