# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_transfer_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('Withdrawals', (('USD', 'US Dollar'),)), ('Deposits', (('USD', 'US Dollar'), ('BTC', 'Bitcoin')))], max_length=4),
        ),
    ]
