# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20171021_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
