# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171023_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
