version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/src/staticfiles
    depends_on:
      - client
      - server
    command: nginx-debug -g 'daemon off';
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    hostname: client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/client
    command: npm run dev
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    volumes:
      - ./server:/usr/src/server
      - staticfiles:/usr/src/staticfiles
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file: .env
    entrypoint: /usr/src/server/docker-entrypoint.sh
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
  worker:
    build:
      context: ./server
    env_file: .env
    command: celery -A polyledger worker -l info
    volumes:
      - ./server:/usr/src/server
    depends_on:
      - server
      - redis

volumes:
  staticfiles:
