# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='date',
            new_name='timestamp',
        ),
    ]
