# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 22:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='risk_score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
