# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='user_agent',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
