# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 16:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=5)),
                ('label', models.CharField(max_length=255)),
                ('sync_progress', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sync_progress', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='base_size',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='base',
            field=models.CharField(default=0, max_length=5, validators=[django.core.validators.RegexValidator('[A-Z]+')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='quote',
            field=models.CharField(default=0, max_length=5, validators=[django.core.validators.RegexValidator('[A-Z]+')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='quote_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('exchange_deposit', 'Exchange Deposit'), ('exchange_withdrawal', 'Exchange Withdrawal'), ('address_withdrawal', 'Address Withdrawal'), ('address_deposit', 'Address Deposit'), ('internal_address_withdrawal', 'Internal Address Withdrawal'), ('internal_address_deposit', 'Internal Address Deposit')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
