# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('date', 'coin')]),
        ),
    ]
