# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171101_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='timestamp',
            new_name='date',
        ),
    ]
