# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180524_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
