# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ipaddress_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='region',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
