# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180416_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_currency', models.CharField(choices=[('usd', 'USD')], max_length=255)),
                ('time_zone', models.CharField(choices=[('pst', 'PST')], max_length=255)),
                ('email_notification', models.CharField(choices=[('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('off', 'Off')], max_length=255)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
