# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180123_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
