# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-22 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180422_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together=set([('ip', 'user', 'user_agent')]),
        ),
    ]
