# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180123_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
