# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171211_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='BCH',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='BTC',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='DASH',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='ETC',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='ETH',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='LTC',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='NEO',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='XMR',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='XRP',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='ZEC',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
