# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180522_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedaddress',
            name='sync_progress',
        ),
        migrations.RemoveField(
            model_name='connectedaddress',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='connectedexchange',
            name='sync_progress',
        ),
        migrations.RemoveField(
            model_name='connectedexchange',
            name='synced_at',
        ),
    ]
