# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180124_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
