# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180422_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedEmail',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
