# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_legal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_notification',
            field=models.CharField(choices=[('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('off', 'Off')], default='weekly', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='local_currency',
            field=models.CharField(choices=[('usd', 'USD (United States dollar)')], default='usd', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='time_zone',
            field=models.CharField(choices=[('pst', 'US/Pacific'), ('utc', 'UTC')], default='pst', max_length=255),
        ),
    ]
