# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180523_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitbutter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='usd',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='legal_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='bitbutter_api_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bitbutter_secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bitbutter_user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.DeleteModel(
            name='Bitbutter',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
    ]
