# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171211_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ADA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='EOS',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='XLM',
            field=models.FloatField(null=True),
        ),
    ]
