# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180124_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_funding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='risk_assessment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
