# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171213_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='BTS',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='KNC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='MCO',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='NXT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='OMG',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='QTUM',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='SC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='SNT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='STORJ',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='VTC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='XEM',
            field=models.FloatField(null=True),
        ),
    ]
