# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 20:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180124_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_funding_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='risk_assessment_complete',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
