# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171213_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
