# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180126_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=255)),
                ('coinbase_user_id', models.CharField(max_length=255)),
                ('coinbase_account_id', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('coin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=255)),
                ('coinbase_user_id', models.CharField(max_length=255)),
                ('coinbase_account_id', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('coin', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='base',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quote',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='buy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.CharField(default='BTC', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='completed', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Transaction'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Transaction'),
        ),
    ]
