# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180126_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='My Portfolio', max_length=100),
        ),
    ]
