# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180214_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
