# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_whitelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whitelist',
            new_name='WhitelistedEmail',
        ),
    ]
