# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180220_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhitelistedEmail',
        ),
    ]
