# -*- coding: utf-8 -*-

# Generated by Django 1.11.5 on 2017-10-30 01:58
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('BTC', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ETH', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('LTC', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('base', models.CharField(choices=[('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin')], max_length=4)),
                ('quote', models.CharField(choices=[('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin')], max_length=4)),
                ('pair', models.CharField(choices=[('BTC-USD', 'Bitcoin - US Dollar'), ('ETH-USD', 'Ethereum - US Dollar'), ('LTC-USD', 'Litecoin - US Dollar'), ('ETH-BTC', 'Ethereum - Bitcoin'), ('LTC-BTC', 'Litecoin - Bitcoin')], max_length=9)),
                ('exchange', models.CharField(choices=[('GDAX', 'GDAX')], max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('settled', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_basis', models.DecimalField(decimal_places=16, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fees', models.DecimalField(decimal_places=16, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_basis_usd', models.DecimalField(decimal_places=16, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fees_usd', models.DecimalField(decimal_places=16, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
