# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='AVT',
        ),
        migrations.RemoveField(
            model_name='price',
            name='BCH',
        ),
        migrations.RemoveField(
            model_name='price',
            name='BCU',
        ),
        migrations.RemoveField(
            model_name='price',
            name='DSH',
        ),
        migrations.RemoveField(
            model_name='price',
            name='EOS',
        ),
        migrations.RemoveField(
            model_name='price',
            name='ETC',
        ),
        migrations.RemoveField(
            model_name='price',
            name='ETP',
        ),
        migrations.RemoveField(
            model_name='price',
            name='IOT',
        ),
        migrations.RemoveField(
            model_name='price',
            name='NEO',
        ),
        migrations.RemoveField(
            model_name='price',
            name='OMG',
        ),
        migrations.RemoveField(
            model_name='price',
            name='QTM',
        ),
        migrations.RemoveField(
            model_name='price',
            name='SAN',
        ),
        migrations.RemoveField(
            model_name='price',
            name='USDT',
        ),
        migrations.RemoveField(
            model_name='price',
            name='XMR',
        ),
        migrations.RemoveField(
            model_name='price',
            name='XRP',
        ),
        migrations.RemoveField(
            model_name='price',
            name='ZEC',
        ),
        migrations.AlterField(
            model_name='trade',
            name='base_coin',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin')], max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='counter_coin',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin')], max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exchange',
            field=models.CharField(choices=[('GDAX', 'GDAX')], max_length=255),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pair',
            field=models.CharField(choices=[('BTC/USD', 'Bitcoin - US Dollar'), ('ETH/USD', 'Ethereum - US Dollar'), ('LTC/USD', 'Litecoin - US Dollar'), ('ETH/BTC', 'Ethereum - Bitcoin'), ('LTC/BTC', 'Litecoin - Bitcoin')], max_length=9),
        ),
    ]
