# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0002_auto_20171017_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='base_coin',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='counter_coin',
            new_name='quote',
        ),
    ]
