# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0004_auto_20171026_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(default='pending', max_length=30),
            preserve_default=False,
        ),
    ]
