# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 03:10
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0005_auto_20171026_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='fees',
            field=models.DecimalField(decimal_places=16, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fees_usd',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=16, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))]), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
