# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0008_auto_20171027_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='base',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin')], max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quote',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin')], max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
    ]
