// Authentication
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const ACTIVATE = "ACTIVATE";
export const LOGOUT = "LOGOUT";

// Analytics
export const FETCH_PORTFOLIO_BENCHMARKS = "FETCH_PORTFOLIO_BENCHMARKS";
export const FETCH_PORTFOLIO_METRICS = "FETCH_PORTFOLIO_METRICS";

// Accounts
export const LINK_EXCHANGE = "LINK_EXCHANGE";
export const LINK_ADDRESS = "LINK_ADDRESS";
export const UNLINK_EXCHANGE = "UNLINK_EXCHANGE";
export const UNLINK_ADDRESS = "UNLINK_ADDRESS";

// Markets
export const FETCH_MARKETS = "FETCH_MARKETS";

// Settings
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const UPDATE_GENERAL_PREFERENCES = "UPDATE_GENERAL_PREFERENCES";
export const UPDATE_NOTIFICATION_PREFERENCES =
  "UPDATE_NOTIFICATION_PREFERENCES";
export const ENABLE_TWO_FACTOR_AUTHENTICATION =
  "ENABLE_TWO_FACTOR_AUTHENTICATION";
export const CREATE_API_KEY = "CREATE_API_KEY";
export const DELETE_API_KEY = "DELETE_API_KEY";
export const CLOSE_ACCOUNT = "CLOSE_ACCOUNT";
