// Alerts
export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const CLEAR_ALERTS = "CLEAR_ALERTS";

// Portfolio
export const REQUEST_PORTFOLIO = "REQUEST_PORTFOLIO";
export const RECEIVE_PORTFOLIO = "RECEIVE_PORTFOLIO";
export const REQUEST_CHART_DATA = "REQUEST_CHART_DATA";
export const RECEIVE_CHART_DATA = "RECEIVE_CHART_DATA";

// Analytics
export const FETCH_PORTFOLIO_BENCHMARKS = "FETCH_PORTFOLIO_BENCHMARKS";
export const FETCH_PORTFOLIO_METRICS = "FETCH_PORTFOLIO_METRICS";

// Accounts
export const REQUEST_CONNECTED_EXCHANGES = "REQUEST_CONNECTED_EXCHANGES";
export const RECEIVE_CONNECTED_EXCHANGES = "RECEIVE_CONNECTED_EXCHANGES";
export const REQUEST_EXCHANGES = "REQUEST_EXCHANGES";
export const RECEIVE_EXCHANGES = "RECEIVE_EXCHANGES";
export const CONNECT_EXCHANGE_SUCCESS = "CONNECT_EXCHANGE_SUCCESS";
export const DISCONNECT_EXCHANGE_SUCCESS = "DISCONNECT_EXCHANGE_SUCCESS";

// Markets
export const FETCH_MARKETS = "FETCH_MARKETS";

// Settings
export const REQUEST_SETTINGS = "REQUEST_SETTINGS";
export const RECEIVE_SETTINGS = "RECEIVE_SETTINGS";
export const UPDATE_PERSONAL_DETAILS = "UPDATE_PERSONAL_DETAILS";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_GENERAL_PREFERENCES = "UPDATE_GENERAL_PREFERENCES";
export const UPDATE_NOTIFICATION_PREFERENCES =
  "UPDATE_NOTIFICATION_PREFERENCES";
export const ENABLE_TWO_FACTOR_AUTHENTICATION =
  "ENABLE_TWO_FACTOR_AUTHENTICATION";
export const CREATE_API_KEY = "CREATE_API_KEY";
export const DELETE_API_KEY = "DELETE_API_KEY";
export const CLOSE_ACCOUNT = "CLOSE_ACCOUNT";

// User
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const ACTIVATE = "ACTIVATE";
export const LOGOUT = "LOGOUT";
