# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 22:43
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('BTC', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ETH', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('BCH', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('XRP', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('LTC', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('DASH', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ZEC', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('XMR', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ETC', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('NEO', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
    ]
