# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
