# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockportfolio',
            name='coins',
            field=models.ManyToManyField(blank=True, related_name='mock_portfolios', through='account.MockPosition', to='account.Coin'),
        ),
        migrations.AlterField(
            model_name='mockportfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mock_portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mockposition',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_positions', to='account.Coin'),
        ),
        migrations.AlterModelTable(
            name='mockportfolio',
            table='mock_portfolio',
        ),
        migrations.AlterModelTable(
            name='mockposition',
            table='mock_position',
        ),
    ]
