# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('coin', 'portfolio')]),
        ),
    ]
