# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171202_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_transactions', to='account.Coin')),
            ],
        ),
        migrations.RenameField(
            model_name='mockportfolio',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.Portfolio'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_transactions', to='account.Coin'),
        ),
    ]
