# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171204_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockportfolio',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='mockportfolio',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='mockposition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mockposition',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='mockposition',
            name='mock_portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='My Portfolio', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MockPortfolio',
        ),
        migrations.DeleteModel(
            name='MockPosition',
        ),
    ]
