# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171202_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usd', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MockPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Coin')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MockPortfolio')),
            ],
        ),
        migrations.AddField(
            model_name='mockportfolio',
            name='coins',
            field=models.ManyToManyField(blank=True, through='account.MockPosition', to='account.Coin'),
        ),
        migrations.AddField(
            model_name='mockportfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mockposition',
            unique_together=set([('coin', 'portfolio')]),
        ),
    ]
