# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_portfolio_selected_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='risk_assessment_score',
            field=models.IntegerField(default=0),
        ),
    ]
