# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171110_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
