# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20171128_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
    ]
