# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='risk_assessment_score',
            new_name='risk_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='risk_assessment_complete',
        ),
    ]
