# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:26
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20171130_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='selected_coins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_funded',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coins_selected',
        ),
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bitcoin', 'Bitcoin'), ('bitcoin_cash', 'Bitcoin Cash'), ('dash', 'Dash'), ('ethereum', 'Ethereum'), ('ethereum_classic', 'Ethereum Classic'), ('litecoin', 'Litecoin'), ('monero', 'Monero'), ('neo', 'NEO'), ('ripple', 'Ripple'), ('zcash', 'Zcash')], max_length=84, null=True),
        ),
    ]
