# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171130_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('symbol', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('percent', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='bitcoin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='bitcoin_cash',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='dash',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ethereum',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ethereum_classic',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='litecoin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='monero',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='neo',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ripple',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='zcash',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coins',
            field=models.ManyToManyField(to='account.Coin'),
        ),
    ]
