# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20171201_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='allocations',
        ),
        migrations.AddField(
            model_name='coin',
            name='percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coins',
            field=models.ManyToManyField(to='account.Coin'),
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
    ]
