# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20171201_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='percent',
        ),
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.FileField(null=True, upload_to='coins/'),
        ),
        migrations.AddField(
            model_name='coin',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
