# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 04:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20171201_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='allocation',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0,0', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
