# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_portfolio_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='allocation',
        ),
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.FilePathField(null=True, path='account/static/account/img/coins/'),
        ),
        migrations.AddField(
            model_name='holdings',
            name='coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Coin'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='holdings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Holdings'),
        ),
    ]
