# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20171201_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Coin')),
            ],
        ),
        migrations.RemoveField(
            model_name='holdings',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='holdings',
        ),
        migrations.DeleteModel(
            name='Holdings',
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Portfolio'),
        ),
    ]
