# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20171201_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='image',
        ),
        migrations.AddField(
            model_name='coin',
            name='image_url',
            field=models.FilePathField(null=True, path='/static/account/img/coins/'),
        ),
    ]
